_BASE_: "../Base-RetinaNet-q.yaml"
MODEL:
  EXTRA_WEIGHTS: "/home/liujing/Models/retinanet/retinanet_R_34_FPN_1x-FPN_BN-Head_GN/model_final.pth"
  WEIGHTS: "/home/liujing/Models/resnet34_2bit_dorefa_clip_71.54_detectron.pth"
  RESNETS:
    DEPTH: 34
    RES2_OUT_CHANNELS: 64
    NORM: "BN"
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "BN"
    USE_RELU: True
  RETINANET:
    NORM: "GN"
  QUANTIZATION:
    fm_bit: 2.0
    wt_bit: 2.0
OUTPUT_DIR: output/coco-detection/retinanet_R_34_FPN_1x-FPN_BN-Head_GN_dorefa_clip
