_BASE_: "../Base-RetinaNet-q.yaml"
MODEL:
  EXTRA_WEIGHTS: "/home/liujing/Codes/detections/Adelaidet-Quantization/output/coco-detection/retinanet_R_18_1x_Full_BN/model_final.pth"
  # WEIGHTS: "/home/liujing/Models/resnet18_3bit_dorefa_clip_69.966_detectron.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  RETINANET:
    NORM: "SyncBN"
    SHARED_NORM: False
  QUANTIZATION:
    fm_bit: 2.0
    wt_bit: 2.0
OUTPUT_DIR: output/coco-detection/retinanet_R_18_1x_Full_BN_dorefa_clip_2bit_no_lp_pretrained
