_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  #WEIGHTS: "weights/det-resnet18/official-r18.pth.raw"
  WEIGHTS: "weights/det-resnet18/dali-dorefa-tet-wt_mean_var-finetune-2bit-wd2e-5-sgd_9-O1-model_best.pth.tar"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "BN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  CLS:
    VERBOSE: True
  QUANTIZATION:
    keyword: ["custom-update", "debug", "dorefa", 'tet']
    fm_enable: True 
    fm_bit: 2.0
    fm_boundary: 4.0
    wt_enable: True 
    wt_bit: 2.0
    wt_boundary: 1.0
    wt_adaptive: "mean-var"
SOLVER:
  IMS_PER_BATCH: 4
OUTPUT_DIR: output/coco-detection/retinanet_R_18_FPN_1x-dorefa-tet
