_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_retinanet_resnet_ofa_fpn_backbone"
    FREEZE_AT: 0
  WEIGHTS: "weights/det-resnet18/official-r18.pth.raw"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  RETINANET:
    NORM: "SyncBN"
SOLVER:
  IMS_PER_BATCH: 1
OUTPUT_DIR: output/coco-detection/retinanet_R_18_1x_Full_SyncBN_ofa_debug
