_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_retinanet_resnet_teacher_fpn_backbone"
    FREEZE_AT: 0
#  WEIGHTS: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/Adelaidet-Quantization/output/coco-detection/retinanet_R_18_1x_Full_SyncBN_teacher_executable/model_final.pth"
  WEIGHTS: "/mnt/cephfs/home/liuxu/code/python/workspace-detection-superclass/Adelaidet-Quantization/output/coco-detection/retinanet_R_18_1x_Full_SyncBN_teacher/model_final.pth"
#  WEIGHTS: "weights/det-resnet18/official-r18.pth.raw"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  RETINANET:
    NORM: "SyncBN"
SOLVER:
  IMS_PER_BATCH: 12
OUTPUT_DIR: output/coco-detection/retinanet_R_18_1x_Full_SyncBN_teacher #_executable
