_BASE_: "Base-550-Aux.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet18/official-r18.pth.raw"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    NORM: "BN"
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  fp16: True
OUTPUT_DIR: "output/coco-instance-segmentation/blendmask_550_R_18_aux_1x-fpn-syncbn-fp16"
