_BASE_: "Base-BlendMask-Aux.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FCOS:
    USE_DEFORMABLE: True
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/blendmask/R_101_bdcn_3x"
