_BASE_: "Base-BlendMask-Aux.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BASIS_MODULE:
    NUM_BASES: 8
OUTPUT_DIR: "output/blendmask/R_50_8_aux_1x"
