_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "weights/det-resnet50/official-r50.pth.raw"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "BN"
  BACKBONE:
    FREEZE_AT: 0
OUTPUT_DIR: output/coco-instance-segmentation/mask-rcnn_R_50_FPN_1x
