_BASE_: "Base-LightHead.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (180000, 240000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/lighthead/R_101_3x"
