_BASE_: "Base-LightHead.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    NUM_CLS_CONVS: 0
    NUM_BOX_CONVS: 0
    NUM_SHARE_CONVS: 4
OUTPUT_DIR: "output/lighthead/R_50_s_1x"
