_BASE_: "Base-LightHead.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (180000, 240000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/lighthead/R_50_3x"
