_BASE_: "Base-LightHead.yaml"
MODEL:
  WEIGHT: "weights/resnet50_lpf3.pth"
  BACKBONE:
    NAME: "build_fcos_resnet_lpf_fpn_backbone"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (180000, 240000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/nobox/R_50_lpf_3x"
