_BASE_: "Base-LightHead.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    INFERENCE_TH: 0.03
    PRE_NMS_TOPK_TRAIN: 12000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 1000
OUTPUT_DIR: "output/lighthead/R_50_more_1x"
