_BASE_: "Base-LightHead.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  LIGHT_HEAD:
    POOLER_RESOLUTION: 7
OUTPUT_DIR: "output/lighthead/R_50_7_1x"
