_BASE_: "Base-FCOS-q.yaml"
MODEL:
  EXTRA_WEIGHTS: "/home/liujing/Models/R_50_1x-FPN_BN-FCOS-BN/model_final.pth"
  WEIGHTS: "/home/liujing/Models/resnet50_2bit_dorefa_clip_73.798_detectron.pth"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  PROPOSAL_GENERATOR:
    NAME: "QFCOS"
  FCOS:
    NORM: "GN"
  QUANTIZATION:
    fm_bit: 2.0
    wt_bit: 2.0
    NOT_SHARED_NORM_HEAD: False
    USE_SIGMOID_QUANTIZATION: False
    USE_UNIROM_QUANTIZATION: True
    T: 3.0
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_50_1x-FPN_BN-FCOS-GN-dorefa-clip"
