_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "/fast/users/a1675776/liujing/models/resnet18_detectron.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  FCOS:
    NORM: "SyncBN"
    SHARED_NORM: False
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_18_1x-Full_SyncBN"
