_BASE_: "Base-FCOS.yaml"
MODEL:
  #WEIGHTS: "weights/det-resnet18/official-r18.pth.raw"
  EXTRA_WEIGHTS: "/home/liujing/Models/chenpeng/model_final.pth"
  WEIGHTS: "/home/liujing/Models/chenpeng/dali-dorefa-wtet-wt_var-finetune-2bit-wd2e-5-sgd_9-O1-model_best.pth.tar"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "BN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "BN"
    USE_RELU: True
  FCOS:
    NORM: "GN"
  fp16: False
  QUANTIZATION:
    scope: [
            'backbone.bottom_up.res2',
            'backbone.bottom_up.res3',
            'backbone.bottom_up.res4',
            'backbone.bottom_up.res5',
            # continue for more branch
            # FPN
            'backbone.fpn_lateral3',
            'backbone.fpn_output3',
            'backbone.fpn_lateral4',
            'backbone.fpn_output4',
            'backbone.fpn_lateral5',
            'backbone.fpn_output5',
            'backbone.top_block',
            # Head tower
            'proposal_generator.fcos_head.cls_tower',
            'proposal_generator.fcos_head.bbox_tower',
           ]
    keyword: ["custom-update", "debug", "dorefa", "tet_nonuniform_hybrid_grad", "wtet_nonuniform"]
    fm_enable: True 
    wt_enable: True 
    fm_bit: 2.0
    wt_bit: 2.0
    fm_boundary: 4.0
    wt_boundary: 1.0
    wt_adaptive: "var"
    wt_T: 3.0
    fm_T: 3.0
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_18_1x-FPN_BN-dorefa-nonuniform-fixed-memory-hybrid-grad-wowd-T3.0-backbone-fpn-head"
