_BASE_: "Base-FCOS-q.yaml"
MODEL:
  #WEIGHTS: "weights/det-resnet18/official-r18.pth.raw"
  # EXTRA_WEIGHTS: "/home/liujing/Codes/detections/Adelaidet-Quantization/output/fcos/R_18_1x-FPN_BN-FCOS-Notshared-BN/model_final.pth"
  # WEIGHTS: "/home/liujing/models/resnet18_2bit_dorefa_clip_67.432_detectron2.pth"
  WEIGHTS: "/home/liujing/Codes/detections/Adelaidet-Quantization/output/fcos/R_18_1x-FPN_BN_fcos_BN-dorefa-backbone-fpn-head/model_0059999.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "BN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "BN"
    USE_RELU: True
  PROPOSAL_GENERATOR:
    NAME: "QFCOS"
  FCOS:
    NORM: "BN"
  fp16: False
  QUANTIZATION:
    fm_bit: 2.0
    wt_bit: 2.0
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_18_1x-FPN_BN_fcos_BN-dorefa-backbone-fpn-head-resume"
