_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "/fast/users/a1675776/liujing/models/resnet50_detectron.pth"
  RESNETS:
    DEPTH: 50
    NORM: "BN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "BN"
    USE_RELU: True
  FCOS:
    NORM: "BN"
    SHARED_NORM: False
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_50_1x-Full_BN"
