_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "/fast/users/a1675776/liujing/detections/Adelaidet-Quantization/output/fcos/R_18_1x-FPN_BN-FCOS-BN/model_0029999.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "BN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "BN"
    USE_RELU: True
  FCOS:
    NORM: "BN"
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_18_1x-FPN-BN-FCOS-BN-resume"
