_BASE_: "Base-FCOS-q.yaml"
MODEL:
  WEIGHTS: "/home/liujing/Codes/detections/Adelaidet-Quantization/output/fcos/R18/R_18_1x-Full_SyncBN_dorefa_clip/model_final.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  PROPOSAL_GENERATOR:
    NAME: "QFCOS"
  FCOS:
    NORM: "SyncBN"
    SHARED_NORM: False
  fp16: False 
  QUANTIZATION:
    fm_bit: 2.0
    wt_bit: 2.0
    NOT_SHARED_NORM_HEAD: False
    USE_SIGMOID_QUANTIZATION: False
    USE_UNIROM_QUANTIZATION: True
    QUANTIZE_FIRST_AND_LAST: False
    T: 3.0
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_18_1x-Full_SyncBN_dorefa_clip_2bit_test"
