_BASE_: "Base-FCOS.yaml"
MODEL:
  #WEIGHTS: "weights/det-resnet18/official-r18.pth.raw"
  WEIGHTS: "weights/det-resnet18/dali-popcount-finetune-ter-s0.625-wt_mean-var-sgd_3-O1-model_best.pth.tar"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "BN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  QUANTIZATION:
    scope: [
            'backbone.bottom_up.res2',
            'backbone.bottom_up.res3',
            'backbone.bottom_up.res4',
            'backbone.bottom_up.res5',
           ]
    keyword: ["custom-update", "debug", "popcount"]
    stable: 80
    fm_enable: True 
    fm_bit: 1.6
    fm_scale: 0.625
    wt_enable: True 
    wt_bit: 1.6
    wt_scale: 0.625
    wt_adaptive: "mean-var"
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
OUTPUT_DIR: output/fcos/R_18_1x-popcount-backbone-only
