_BASE_: "Base-FCOS-q.yaml"
MODEL:
  EXTRA_WEIGHTS: "/fast/users/a1675776/liujing/models/R_50_1x-Full_BN/model_final.pth"
  # WEIGHTS: "/fast/users/a1675776/liujing/models/resnet50_2bit_dorefa_clip_73.798_detectron.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "SyncBN"
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  PROPOSAL_GENERATOR:
    NAME: "QFCOS"
  FCOS:
    NORM: "SyncBN"
    SHARED_NORM: False
  QUANTIZATION:
    fm_bit: 4.0
    wt_bit: 4.0
    NOT_SHARED_NORM_HEAD: False
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output/fcos/R_50_1x-FPN_SyncBN-FCOS-SyncBN_no_lp_pretrained_4bit_act_val_3"
